### ISSUE TITLE
NaudioPlayer requires "MyLibrary"

### ISSUE THREAD

**Issue by BerdinEge** [aykanatm/NaudioPlayer#1]
I downloaded the code and try to build on visual studio. There are 3 unloaded projects named "MyLibrary.CustomCollections", "MyLibrary.CustomMath", "MyLibrary.StringOperations". NaudioWrapper and NaudioPlayer loaded correctly but there are errors on the build cause of the "MyLibrary" classes. How can i get this library or just exact classes to run the NaudioPlayer ?

**Comment by steven-groban** [comment]
MyLibrary.CustomCollections

**Comment by steven-groban** [comment]
MyLibrary.StringOperations
